# Generated by Django 6.1.1 on 2026-09-08 08:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_released_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("GENESIS", "Genesis"),
                    ("FUND", "Funding Deposit"),
                    ("RELEASE", "Stage Release"),
                    ("REFUND", "Backer Refund"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="FundingStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "released_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOCKED", "Locked"),
                            ("READY", "Ready for Progress Update"),
                            ("VOTING", "Voting in Progress"),
                            ("RELEASED", "Released"),
                        ],
                        default="LOCKED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["stage_number"],
            },
        ),
        migrations.AddField(
            model_name="block",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="release_blocks",
                to="core.fundingstage",
            ),
        ),
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("evidence_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Vote"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="core.fundingstage",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="block",
            name="progress_update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="release_blocks",
                to="core.progressupdate",
            ),
        ),
        migrations.CreateModel(
            name="ProgressVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("GREEN", "Approve"), ("RED", "Reject")], max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "progress_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.progressupdate",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fundingstage",
            constraint=models.UniqueConstraint(
                fields=("project", "stage_number"), name="unique_project_stage_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("stage_number__gte", 1), ("stage_number__lte", 4)),
                name="stage_number_between_one_and_four",
            ),
        ),
        migrations.AddConstraint(
            model_name="progressvote",
            constraint=models.UniqueConstraint(
                fields=("progress_update", "voter"),
                name="one_vote_per_progress_update_user",
            ),
        ),
    ]
