# Generated by Django 6.1.1 on 2026-09-08 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_total_released_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
