# Generated by Django 6.1.1 on 2026-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_block_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingstage",
            name="rejection_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fundingstage",
            name="status",
            field=models.CharField(
                choices=[
                    ("LOCKED", "Locked"),
                    ("READY", "Ready for Progress Update"),
                    ("VOTING", "Voting in Progress"),
                    ("RELEASED", "Released"),
                    ("FAILED", "Failed and Refunded"),
                ],
                default="LOCKED",
                max_length=10,
            ),
        ),
    ]
